### ISSUE TITLE
Fully build on Docker Hub

### ISSUE THREAD

**Issue by stefandevo** [Arbify/Arbify#30]
It would be great if you could provide a docker-compose that is available on Docker-hub with the latest build version.
I want to deploy this on a semi-public host but now it takes a very long time to download, build and startup. The startup itself is taking a very long time, and I see hundreds of lines in the log before it can start.
So it would be great to have a running version available.

**Comment by Albert221** [comment]
Thank you for your feedback!

I'm aware that deploying Arbify currently takes so much time (downloading and compiling frontend stuff...), but as of now, Arbify is still under heavy development. Once Arbify will start to be versioned and have releases and tags, providing a better experience in deploying will be a must-do. Hopefully, this will take place soon :)

I hope that current build times won't take your interest in Arbify away though.

**Comment by stefandevo** [comment]
Hi @Albert221 do you have any idea when a prebuild Docker is available to use?

**Comment by Albert221** [comment]
Hi! Full Docker build probably won't be available as an image on Docker Hub. It's due to the nature of the image itself. It mounts the cloned files as a volume that allows for easy upgrades in the future.

Since my last response, I managed to clean up a bit on how docker deployment looks like. Now it doesn't take ages for simply running already set up Arbify.

```bash
docker-compose build arbify
docker-compose up -d
docker-compose run --rm arbify docker/arbify/upgrade.sh
```

Where the first and last commands are only needed for installing/upgrading. If you need to start the app, you just need to run `docker-compose up -d`. As simple as that.

I hope this solution is enough for you for this time.
